### PR TITLE
Use paper tick times method when available

### LINKED ISSUE #208: [Bug Report] [1.20.4] Failed to find tick times buffer via reflection.
### Logs

```
...
minecraft-prometheus-exporter-mc-1  | [17:51:53 INFO]: This server is running Paper version git-Paper-366 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 983377b)
...
minecraft-prometheus-exporter-mc-1  | [17:51:57 INFO]: [PrometheusExporter] Enabling PrometheusExporter v2.6.0
minecraft-prometheus-exporter-mc-1  | [17:51:57 WARN]: [PrometheusExporter] Failed to find tick times buffer via reflection. Tick duration metrics will not be available.
```

### Further Context

This happens on 1.20.4 but not on any previous version. The tick times metric is unavailable but the rest of the plugin works.

### PR DESCRIPTION
**Pull request by radiant-ai**
Partially fixes #208 by a use of Paper https://jd.papermc.io/paper/1.20/org/bukkit/Bukkit.html#getTickTimes()

I use this on my servers since 1.20.4 update and decided to share it

### CODE REVIEW

**Comment by sladkoff** [comment]
@radiant-ai Thanks for the contribution! ⭐ 

This also fixes https://github.com/sladkoff/minecraft-prometheus-exporter/issues/155, right?

**Comment by radiant-ai** [comment]
> @radiant-ai Thanks for the contribution! ⭐
> 
> This also fixes #155, right?

Sorry, I did a mistake and accidentally merged experimental fix to async world size calculation there. I will revert that commit for now as it has some issues.

**Comment by radiant-ai** [comment]
Now this includes only paper tick times support. I will fix world size calculation later and open another PR for that.

**Comment by sladkoff** [comment]
@radiant-ai No problem at all! Looking forward to your next PR then :)

**Pull request merged**
